---
- name: Configure global settings
  ansible.builtin.template:
    src: "postgresql-{{ postgresql_version }}.conf.j2"
    dest: "{{ postgresql_conf_dir }}/postgresql.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  notify:
    - restart postgresql

- name: Configure host based authentication
  template: 
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_conf_dir }}/pg_hba.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0600
  notify:
    - restart postgresql

- name: Ensure that service is started and enabled on boot.
  ansible.builtin.systemd_service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true
